name: rejection
channels:
  - anaconda
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - astor=0.8.1
  - asttokens=2.4.1
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - cached_property=1.5.2
  - certifi=2024.8.30
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.3.0
  - cycler=0.12.1
  - debugpy=1.8.8
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - fonttools=4.54.1
  - formulaic=1.0.2
  - freetype=2.12.1
  - fuzzywuzzy=0.18.0
  - graphlib-backport=1.0.3
  - importlib-metadata=8.5.0
  - interface_meta=1.3.0
  - ipykernel=6.29.5
  - ipython=8.29.0
  - jedi=0.19.1
  - joblib=1.4.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - keyutils=1.6.1
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.16
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - levenshtein=0.26.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libdeflate=1.22
  - libedit=3.1.20191231
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libgomp=14.2.0
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libmpdec=4.0.0
  - libopenblas=0.3.28
  - libpng=1.6.44
  - libsodium=1.0.20
  - libsqlite=3.47.0
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libwebp-base=1.4.0
  - libxcb=1.17.0
  - libxml2=2.13.4
  - libxslt=1.1.41
  - libzlib=1.3.1
  - linearmodels=6.1
  - lxml=5.2.1
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.7
  - munkres=1.1.4
  - mypy_extensions=1.0.0
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - numpy=2.1.3
  - openjpeg=2.5.2
  - openssl=3.3.2
  - packaging=24.1
  - pandas=2.2.3
  - parso=0.8.4
  - patsy=0.5.6
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.0.0
  - pip=24.3.1
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.48
  - psutil=6.1.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.18.0
  - pyhdfe=0.2.0
  - pyparsing=3.2.0
  - python=3.13.0
  - python-dateutil=2.9.0
  - python-levenshtein=0.26.1
  - python-tzdata=2024.2
  - python_abi=3.13
  - pytz=2024.1
  - pyzmq=26.2.0
  - qhull=2020.2
  - rapidfuzz=3.10.1
  - readline=8.2
  - scikit-learn=1.5.2
  - scipy=1.14.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=75.3.0
  - six=1.16.0
  - stack_data=0.6.2
  - statsmodels=0.14.4
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - tornado=6.4.1
  - tqdm=4.67.0
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024b
  - wcwidth=0.2.13
  - wrapt=1.16.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.5
  - xz=5.2.6
  - zeromq=4.3.5
  - zipp=3.21.0
  - zstd=1.5.6
